//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        public Cuenta()
        {
            this.AtributoPersonalizado = new HashSet<AtributoPersonalizado>();
            this.Categoria = new HashSet<Categoria>();
            this.Producto = new HashSet<Producto>();
            this.Relacion = new HashSet<Relacion>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<AtributoPersonalizado> AtributoPersonalizado { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Relacion> Relacion { get; set; }
    }
}
