//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ProductoAtributo = new HashSet<ProductoAtributo>();
            this.Categoria = new HashSet<Categoria>();
        }
    
        public string sku { get; set; }
        public string gtin { get; set; }
        public string label { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<System.DateTime> ultimaModificacion { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public Nullable<int> espacioOcupado { get; set; }
        public byte[] thumbnail { get; set; }
    
        public virtual ICollection<ProductoAtributo> ProductoAtributo { get; set; }
        public virtual ICollection<Categoria> Categoria { get; set; }
    }
}
