//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniPIM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relacion
    {
        public Relacion()
        {
            this.RelacionProducto = new HashSet<RelacionProducto>();
        }
    
        public string nombre { get; set; }
        public int cuenta_id { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual ICollection<RelacionProducto> RelacionProducto { get; set; }
    }
}
